"use client";
import { Minus, Plus, Trash2 } from "lucide-react";import { useMemo,useRef,useState } from "react";import { useRouter } from "next/navigation";import { toast } from "sonner";import { createClient } from "@/lib/supabase/client";import { money } from "@/lib/utils";
type Option={id:string;name?:string;full_name?:string;sale_price?:number;stock_quantity?:number};type Line={product_id:string;quantity:number;discount:number};type Payment={payment_method_id:string;amount:number;installments:number};
export function SaleForm({customers,employees,products,paymentMethods,selectedCustomer}:{customers:Option[];employees:Option[];products:Option[];paymentMethods:Option[];selectedCustomer?:string}){
 const router=useRouter();const key=useRef(crypto.randomUUID());const [customer,setCustomer]=useState(selectedCustomer||"");const [employee,setEmployee]=useState("");const [items,setItems]=useState<Line[]>([]);const [payments,setPayments]=useState<Payment[]>([{payment_method_id:"",amount:0,installments:1}]);const [discount,setDiscount]=useState(0);const [pending,setPending]=useState(false);
 const subtotal=useMemo(()=>items.reduce((sum,i)=>{const p=products.find(x=>x.id===i.product_id);return sum+i.quantity*Number(p?.sale_price||0)-i.discount},0),[items,products]);const total=Math.max(0,subtotal-discount);
 function addItem(id:string){if(!id)return;setItems(old=>old.some(i=>i.product_id===id)?old:[...old,{product_id:id,quantity:1,discount:0}])}
 function updateLine(index:number,patch:Partial<Line>){setItems(old=>old.map((x,i)=>i===index?{...x,...patch}:x))}
 async function submit(e:React.FormEvent){e.preventDefault();if(!employee||!items.length||payments.some(p=>!p.payment_method_id)||Math.abs(payments.reduce((s,p)=>s+Number(p.amount),0)-total)>.009){toast.error("Revise o responsável, os itens e a soma dos pagamentos.");return}setPending(true);const {data,error}=await createClient().rpc("complete_sale",{p_idempotency_key:key.current,p_customer_id:customer||null,p_employee_id:employee,p_discount:discount,p_notes:"",p_items:items,p_payments:payments});if(error){toast.error(error.message);setPending(false);return}toast.success("Venda concluída e estoque atualizado.");router.push(`/vendas/${data}`);router.refresh()}
 return <form onSubmit={submit} className="grid gap-4"><section className="panel panel-body form-grid"><div className="field"><label>Cliente (opcional)</label><select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Consumidor não identificado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></div><div className="field"><label>Funcionário responsável *</label><select value={employee} onChange={e=>setEmployee(e.target.value)} required><option value="">Selecione</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></div></section>
 <section className="panel"><div className="panel-header"><h2 className="section-title">Produtos</h2></div><div className="panel-body"><div className="field mb-4"><label>Adicionar produto</label><select value="" onChange={e=>addItem(e.target.value)}><option value="">Selecione um produto</option>{products.filter(p=>!items.some(i=>i.product_id===p.id)&&Number(p.stock_quantity)>0).map(p=><option key={p.id} value={p.id}>{p.name} · {p.stock_quantity} un. · {money(p.sale_price)}</option>)}</select></div>{items.length?<div className="data-list">{items.map((item,index)=>{const p=products.find(x=>x.id===item.product_id)!;return <div className="data-card" key={item.product_id}><div className="flex justify-between gap-3"><div><strong>{p.name}</strong><div className="data-card-meta mt-1">{money(p.sale_price)} cada · {p.stock_quantity} disponíveis</div></div><button type="button" className="icon-btn" onClick={()=>setItems(x=>x.filter((_,i)=>i!==index))} aria-label={`Remover ${p.name}`}><Trash2 size={17}/></button></div><div className="flex flex-wrap items-end gap-3"><div className="field"><label>Quantidade</label><div className="flex"><button type="button" className="icon-btn" onClick={()=>updateLine(index,{quantity:Math.max(1,item.quantity-1)})}><Minus size={16}/></button><input style={{width:74,textAlign:"center"}} type="number" min="1" max={p.stock_quantity} step="1" value={item.quantity} onChange={e=>updateLine(index,{quantity:Number(e.target.value)})}/><button type="button" className="icon-btn" onClick={()=>updateLine(index,{quantity:Math.min(Number(p.stock_quantity),item.quantity+1)})}><Plus size={16}/></button></div></div><div className="field"><label>Desconto no item</label><input style={{width:130}} type="number" min="0" step="0.01" value={item.discount} onChange={e=>updateLine(index,{discount:Number(e.target.value)})}/></div><strong className="ml-auto mb-3">{money(item.quantity*Number(p.sale_price)-item.discount)}</strong></div></div>})}</div>:<div className="empty"><strong>Nenhum produto adicionado</strong>Selecione acima para montar a venda.</div>}</div></section>
 <div className="split"><section className="panel"><div className="panel-header"><h2 className="section-title">Pagamentos</h2><button type="button" className="btn btn-secondary" onClick={()=>setPayments(p=>[...p,{payment_method_id:"",amount:0,installments:1}])}><Plus size={16}/>Dividir</button></div><div className="panel-body data-list">{payments.map((pay,i)=><div className="form-grid" key={i}><div className="field"><label>Forma</label><select value={pay.payment_method_id} onChange={e=>setPayments(old=>old.map((p,x)=>x===i?{...p,payment_method_id:e.target.value}:p))}><option value="">Selecione</option>{paymentMethods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="field"><label>Valor</label><div className="flex gap-2"><input type="number" min="0.01" step="0.01" value={pay.amount||""} onChange={e=>setPayments(old=>old.map((p,x)=>x===i?{...p,amount:Number(e.target.value)}:p))}/>{payments.length>1&&<button type="button" className="icon-btn" onClick={()=>setPayments(old=>old.filter((_,x)=>x!==i))}><Trash2 size={16}/></button>}</div></div></div>)}</div></section>
 <section className="panel panel-body"><div className="flex justify-between py-2"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="field py-2"><label>Desconto geral (gerente)</label><input type="number" min="0" max={subtotal} step="0.01" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></div><div className="flex justify-between border-t border-gray-200 mt-3 pt-4 text-xl"><strong>Total</strong><strong>{money(total)}</strong></div><div className="flex justify-between text-sm text-gray-500 py-3"><span>Pagamentos informados</span><span>{money(payments.reduce((s,p)=>s+Number(p.amount),0))}</span></div><button className="btn btn-primary w-full" disabled={pending||!items.length}>{pending?"Concluindo…":"Concluir venda"}</button><p className="text-xs text-gray-500 mt-3">Preços e estoque serão validados novamente pelo servidor.</p></section></div></form>
}
